// Generated by CoffeeScript 1.8.0
(function() {
  var Test, proxy, remote, rpc;

  proxy = require('./ioProxy');

  rpc = new proxy.Client("http://localhost:" + process.argv[2], 'ns');

  Test = (function() {
    function Test() {}

    Test.prototype.echo = function() {
      return "ok";
    };

    return Test;

  })();

  remote = rpc.remote('ns', 'getAge');

  setTimeout((function() {
    console.log("sending getAge - avail: " + rpc.ready);
    return remote.getAge(function(msg, err) {
      if (err) {
        return console.log(err);
      } else {
        return console.log("getAge: " + msg);
      }
    });
  }), 2000);

  rpc.implement('ns', new Test);

}).call(this);
