// Generated by CoffeeScript 1.8.0
(function() {
  var Client, Test, cli;

  Client = require('avs-proxy').Client;

  cli = new Client("http://localhost:" + process.argv[2] + "/ns", function(rpc) {
    var remotec;
    console.log("cli connected!");
    rpc.implement(new Test);
    remotec = rpc.remote('getAge');
    return remotec.getAge(function(rst, err) {
      return console.log(err ? err : "getAge: " + rst);
    });
  });

  Test = (function() {
    function Test() {}

    Test.prototype.echo = function() {
      return "ok";
    };

    return Test;

  })();

}).call(this);
