// Generated by CoffeeScript 1.8.0
(function() {
  var Server, User, srv;

  Server = require('avs-proxy').Server;

  srv = new Server("http://localhost:" + process.argv[2], 'ns', function(rpc, err) {
    var remote;
    if (err) {
      return console.log(err);
    } else {
      rpc.implement(new User('test', 345));
      remote = rpc.remote('echo');
      return setTimeout((function() {
        console.log("sending echo");
        return remote.echo(34, function(rst, err) {
          return console.log(err ? err : "echo: " + rst);
        });
      }), 2000);
    }
  });

  User = (function() {
    function User(name, age) {
      this.name = name;
      this.age = age;
    }

    User.prototype.getAge = function() {
      return this.age;
    };

    return User;

  })();

}).call(this);
