// Generated by CoffeeScript 1.8.0
(function() {
  var User, proxy, server;

  User = (function() {
    function User(name, age) {
      this.name = name;
      this.age = age;
    }

    User.prototype.getAge = function() {
      return this.age;
    };

    return User;

  })();

  proxy = require('./ioProxy');

  server = new proxy.Server("http://localhost:" + process.argv[2], ['ns', 'truc'], function(domain, rpc) {
    var remote;
    rpc.implement(new User('gg', 32));
    remote = rpc.remote('echo');
    return setTimeout((function() {
      console.log("sending echo");
      return remote.echo(function(rst) {
        return console.log("echo: " + rst);
      });
    }), 5000);
  });

}).call(this);
